### ISSUE TITLE
Errors while using make?

### ISSUE THREAD

**Issue by Fazelesswhite** [miguelmartin75/yoloswag420#7]
I guess there was a typo in the makefile which was -std=c++1y I changed it  to -std=c++11 and then tried to make it, still gives me these errors! What am I doing wrong?

root@debian:/usr/src/yoloswag420# make
c++ -std=c++11 -g -I/usr/local/include -I./extlibs/StringUtils/include -Wno-deprecated-register src/Interpreter.cpp src/AST/UnaryOperatorNode.cpp src/AST/IdentifierNode.cpp src/AST/VariableDeclNode.cpp src/AST/CommandNode.cpp src/AST/BinaryOperatorNode.cpp src/AST/Statement.cpp src/lexer.cpp src/main.cpp src/parser.cpp -o ys420i
src/Interpreter.cpp:1:27: fatal error: interpreter.hpp: No such file or directory
compilation terminated.
In file included from src/AST/UnaryOperatorNode.hpp:4:0,
                 from src/AST/UnaryOperatorNode.cpp:1:
src/AST/Node.hpp: In function ‘ast::NodePtr<T> ast::node(Args&& ...)’:
src/AST/Node.hpp:53:16: error: ‘make_unique’ is not a member of ‘std’
src/AST/Node.hpp:53:34: error: expected primary-expression before ‘>’ token
src/AST/Node.hpp:53:60: error: expected ‘)’ before ‘...’ token
src/AST/Node.hpp:53:63: error: parameter packs not expanded with ‘...’:
src/AST/Node.hpp:53:63: note:         ‘args’
src/AST/Node.hpp:53:63: note:         ‘Args’
In file included from src/AST/../Interpreter.hpp:7:0,
                 from src/AST/UnaryOperatorNode.cpp:3:
src/AST/../Logger.hpp: In constructor ‘Logger::Logger(std::ostream&)’:
src/AST/../Logger.hpp:18:39: error: invalid initialization of non-const reference of type ‘std::ostream& {aka std::basic_ostream<char>&}’ from an rvalue of type ‘<brace-enclosed initializer list>’
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-deprecated-register" [enabled by default]
In file included from src/AST/IdentifierNode.hpp:6:0,
                 from src/AST/IdentifierNode.cpp:1:
src/AST/Node.hpp: In function ‘ast::NodePtr<T> ast::node(Args&& ...)’:
src/AST/Node.hpp:53:16: error: ‘make_unique’ is not a member of ‘std’
src/AST/Node.hpp:53:34: error: expected primary-expression before ‘>’ token
src/AST/Node.hpp:53:60: error: expected ‘)’ before ‘...’ token
src/AST/Node.hpp:53:63: error: parameter packs not expanded with ‘...’:
src/AST/Node.hpp:53:63: note:         ‘args’
src/AST/Node.hpp:53:63: note:         ‘Args’
In file included from src/AST/../Interpreter.hpp:7:0,
                 from src/AST/IdentifierNode.cpp:3:
src/AST/../Logger.hpp: In constructor ‘Logger::Logger(std::ostream&)’:
src/AST/../Logger.hpp:18:39: error: invalid initialization of non-const reference of type ‘std::ostream& {aka std::basic_ostream<char>&}’ from an rvalue of type ‘<brace-enclosed initializer list>’
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-deprecated-register" [enabled by default]
In file included from src/AST/VariableDeclNode.cpp:5:0:
src/AST/detail/AssignmentVisitor.hpp:9:54: fatal error: boost/lexical_cast/try_lexical_convert.hpp: No such file or directory
compilation terminated.
In file included from src/AST/CommandNode.hpp:4:0,
                 from src/AST/CommandNode.cpp:1:
src/AST/Node.hpp: In function ‘ast::NodePtr<T> ast::node(Args&& ...)’:
src/AST/Node.hpp:53:16: error: ‘make_unique’ is not a member of ‘std’
src/AST/Node.hpp:53:34: error: expected primary-expression before ‘>’ token
src/AST/Node.hpp:53:60: error: expected ‘)’ before ‘...’ token
src/AST/Node.hpp:53:63: error: parameter packs not expanded with ‘...’:
src/AST/Node.hpp:53:63: note:         ‘args’
src/AST/Node.hpp:53:63: note:         ‘Args’
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-deprecated-register" [enabled by default]
src/AST/BinaryOperatorNode.cpp:6:54: fatal error: boost/lexical_cast/try_lexical_convert.hpp: No such file or directory
compilation terminated.
In file included from src/AST/Statement.hpp:5:0,
                 from src/AST/Statement.cpp:1:
src/AST/Node.hpp: In function ‘ast::NodePtr<T> ast::node(Args&& ...)’:
src/AST/Node.hpp:53:16: error: ‘make_unique’ is not a member of ‘std’
src/AST/Node.hpp:53:34: error: expected primary-expression before ‘>’ token
src/AST/Node.hpp:53:60: error: expected ‘)’ before ‘...’ token
src/AST/Node.hpp:53:63: error: parameter packs not expanded with ‘...’:
src/AST/Node.hpp:53:63: note:         ‘args’
src/AST/Node.hpp:53:63: note:         ‘Args’
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-deprecated-register" [enabled by default]
lexer.l:4:54: fatal error: boost/lexical_cast/try_lexical_convert.hpp: No such file or directory
compilation terminated.
In file included from src/AST/AST.hpp:5:0,
                 from parser.y:26,
                 from src/main.cpp:5:
src/AST/Node.hpp: In function ‘ast::NodePtr<T> ast::node(Args&& ...)’:
src/AST/Node.hpp:53:16: error: ‘make_unique’ is not a member of ‘std’
src/AST/Node.hpp:53:34: error: expected primary-expression before ‘>’ token
src/AST/Node.hpp:53:60: error: expected ‘)’ before ‘...’ token
src/AST/Node.hpp:53:63: error: parameter packs not expanded with ‘...’:
src/AST/Node.hpp:53:63: note:         ‘args’
src/AST/Node.hpp:53:63: note:         ‘Args’
In file included from src/Interpreter.hpp:7:0,
                 from src/main.cpp:7:
src/Logger.hpp: In constructor ‘Logger::Logger(std::ostream&)’:
src/Logger.hpp:18:39: error: invalid initialization of non-const reference of type ‘std::ostream& {aka std::basic_ostream<char>&}’ from an rvalue of type ‘<brace-enclosed initializer list>’
src/main.cpp: In function ‘ast::StatementList parse(const string&, int*)’:
src/main.cpp:79:21: error: ‘yyparse’ was not declared in this scope
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-deprecated-register" [enabled by default]
In file included from src/AST/Statement.hpp:5:0,
                 from src/AST/StatementList.hpp:6,
                 from parser.y:6:
src/AST/Node.hpp: In function ‘ast::NodePtr<T> ast::node(Args&& ...)’:
src/AST/Node.hpp:53:16: error: ‘make_unique’ is not a member of ‘std’
src/AST/Node.hpp:53:34: error: expected primary-expression before ‘>’ token
src/AST/Node.hpp:53:60: error: expected ‘)’ before ‘...’ token
src/AST/Node.hpp:53:63: error: parameter packs not expanded with ‘...’:
src/AST/Node.hpp:53:63: note:         ‘args’
src/AST/Node.hpp:53:63: note:         ‘Args’
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-deprecated-register" [enabled by default]
make: *** [all] Error 1
root@debian:/usr/src/yoloswag420#

**Comment by miguelmartin75** [comment]
>I guess there was a typo in the makefile which was -std=c++1y I changed it to -std=c++11 and then tried to make it, still gives me these errors! What am I doing wrong?

My code is cluttered with `std::make_unique` so you need `-std=c++1y` or `-std=c++14`.

>src/Interpreter.cpp:1:27: fatal error: interpreter.hpp: No such file or directory

Hmm seems that I didn't realise I typed the include with a lower case `i`. I use OS X, which has case in-sensitive file names, so that's why I didn't really notice. I just fixed this.

Here are the things you actually need on your machine to compile it:

- flex
- bison
- boost (I think the only thing I'm using boost for is `boost::lexical_cast`)

The implementation of the language is still not really complete (even with the minimal standard I imposed). The main bugs are: (1) no operator precedence in the parser (as I don't quite understand how to do it with bison yet) and (2) you cannot go `x + y + z` etc (which is quite related to the operator precedence, I *think*); which is quite annoying as you need three separate prints to do `prnt "x is: " + x + "\n" plz`.

**Comment by Fazelesswhite** [comment]
I installed flex, bison and boost using macports and then I also updated my gcc to 4.9 and then the c++1y flag worked too but now I get these errors when I try to make it : 
FaZe-Machine:yoloswag420-master Hayzam$ make
c++ -std=c++1y -g -I/usr/local/include -I./extlibs/StringUtils/include -Wno-deprecated-register src/AST/BinaryOperatorNode.cpp src/AST/CommandNode.cpp src/AST/IdentifierNode.cpp src/AST/Statement.cpp src/AST/UnaryOperatorNode.cpp src/AST/VariableDeclNode.cpp src/Interpreter.cpp src/lexer.cpp src/main.cpp src/parser.cpp -o ys420i
In file included from src/AST/BinaryOperatorNode.cpp:1:
In file included from src/AST/BinaryOperatorNode.hpp:4:
In file included from src/AST/Node.hpp:8:
src/AST/Value.hpp:4:10: fatal error: 'boost/thread/variant.hpp' file not found
#include <boost/thread/variant.hpp>
         ^
1 error generated.
In file included from src/AST/CommandNode.cpp:1:
In file included from src/AST/CommandNode.hpp:4:
In file included from src/AST/Node.hpp:8:
src/AST/Value.hpp:4:10: fatal error: 'boost/thread/variant.hpp' file not found
#include <boost/thread/variant.hpp>
         ^
1 error generated.
In file included from src/AST/IdentifierNode.cpp:1:
In file included from src/AST/IdentifierNode.hpp:6:
In file included from src/AST/Node.hpp:8:
src/AST/Value.hpp:4:10: fatal error: 'boost/thread/variant.hpp' file not found
#include <boost/thread/variant.hpp>
         ^
1 error generated.
In file included from src/AST/Statement.cpp:1:
In file included from src/AST/Statement.hpp:4:
src/AST/Value.hpp:4:10: fatal error: 'boost/thread/variant.hpp' file not found
#include <boost/thread/variant.hpp>
         ^
1 error generated.
In file included from src/AST/UnaryOperatorNode.cpp:1:
In file included from src/AST/UnaryOperatorNode.hpp:4:
In file included from src/AST/Node.hpp:8:
src/AST/Value.hpp:4:10: fatal error: 'boost/thread/variant.hpp' file not found
#include <boost/thread/variant.hpp>
         ^
1 error generated.
In file included from src/AST/VariableDeclNode.cpp:1:
In file included from src/AST/VariableDeclNode.hpp:4:
In file included from src/AST/Node.hpp:8:
src/AST/Value.hpp:4:10: fatal error: 'boost/thread/variant.hpp' file not found
#include <boost/thread/variant.hpp>
         ^
1 error generated.
In file included from src/Interpreter.cpp:1:
In file included from src/interpreter.hpp:9:
In file included from src/AST/AST.hpp:4:
src/AST/Value.hpp:4:10: fatal error: 'boost/thread/variant.hpp' file not found
#include <boost/thread/variant.hpp>
         ^
1 error generated.
lexer.l:4:10: fatal error: 'boost/lexical_cast/try_lexical_convert.hpp' file not found
#include <boost/lexical_cast/try_lexical_convert.hpp>
         ^
1 error generated.
In file included from src/main.cpp:5:
In file included from parser.y:26:
In file included from src/AST/AST.hpp:4:
src/AST/Value.hpp:4:10: fatal error: 'boost/thread/variant.hpp' file not found
#include <boost/thread/variant.hpp>
         ^
1 error generated.
In file included from parser.y:6:
In file included from src/AST/StatementList.hpp:6:
In file included from src/AST/Statement.hpp:4:
src/AST/Value.hpp:4:10: fatal error: 'boost/thread/variant.hpp' file not found
#include <boost/thread/variant.hpp>
         ^
1 error generated.
make: *** [all] Error 1
FaZe-Machine:yoloswag420-master Hayzam$ nano 
CMakeLists.txt  LICENSE.txt     Makefile        README.md       run_samples.sh  samples/        src/            
FaZe-Machine:yoloswag420-master Hayzam$ nano 
CMakeLists.txt  LICENSE.txt     Makefile        README.md       run_samples.sh  samples/        src/            
FaZe-Machine:yoloswag420-master Hayzam$ nano src/AST/Value.hpp
FaZe-Machine:yoloswag420-master Hayzam$ make
c++ -std=c++1y -g -I/usr/local/include -I./extlibs/StringUtils/include -Wno-deprecated-register src/AST/BinaryOperatorNode.cpp src/AST/CommandNode.cpp src/AST/IdentifierNode.cpp src/AST/Statement.cpp src/AST/UnaryOperatorNode.cpp src/AST/VariableDeclNode.cpp src/Interpreter.cpp src/lexer.cpp src/main.cpp src/parser.cpp -o ys420i
In file included from src/AST/BinaryOperatorNode.cpp:1:
In file included from src/AST/BinaryOperatorNode.hpp:4:
In file included from src/AST/Node.hpp:8:
src/AST/Value.hpp:4:10: fatal error: 'boost/variant.hpp' file not found
#include <boost/variant.hpp>
         ^
1 error generated.
In file included from src/AST/CommandNode.cpp:1:
In file included from src/AST/CommandNode.hpp:4:
In file included from src/AST/Node.hpp:8:
src/AST/Value.hpp:4:10: fatal error: 'boost/variant.hpp' file not found
#include <boost/variant.hpp>
         ^
1 error generated.
In file included from src/AST/IdentifierNode.cpp:1:
In file included from src/AST/IdentifierNode.hpp:6:
In file included from src/AST/Node.hpp:8:
src/AST/Value.hpp:4:10: fatal error: 'boost/variant.hpp' file not found
#include <boost/variant.hpp>
         ^
1 error generated.
In file included from src/AST/Statement.cpp:1:
In file included from src/AST/Statement.hpp:4:
src/AST/Value.hpp:4:10: fatal error: 'boost/variant.hpp' file not found
#include <boost/variant.hpp>
         ^
1 error generated.
In file included from src/AST/UnaryOperatorNode.cpp:1:
In file included from src/AST/UnaryOperatorNode.hpp:4:
In file included from src/AST/Node.hpp:8:
src/AST/Value.hpp:4:10: fatal error: 'boost/variant.hpp' file not found
#include <boost/variant.hpp>
         ^
1 error generated.
In file included from src/AST/VariableDeclNode.cpp:1:
In file included from src/AST/VariableDeclNode.hpp:4:
In file included from src/AST/Node.hpp:8:
src/AST/Value.hpp:4:10: fatal error: 'boost/variant.hpp' file not found
#include <boost/variant.hpp>
         ^
1 error generated.
In file included from src/Interpreter.cpp:1:
In file included from src/interpreter.hpp:9:
In file included from src/AST/AST.hpp:4:
src/AST/Value.hpp:4:10: fatal error: 'boost/variant.hpp' file not found
#include <boost/variant.hpp>
         ^
1 error generated.
lexer.l:4:10: fatal error: 'boost/lexical_cast/try_lexical_convert.hpp' file not found
#include <boost/lexical_cast/try_lexical_convert.hpp>
         ^
1 error generated.
In file included from src/main.cpp:5:
In file included from parser.y:26:
In file included from src/AST/AST.hpp:4:
src/AST/Value.hpp:4:10: fatal error: 'boost/variant.hpp' file not found
#include <boost/variant.hpp>
         ^
1 error generated.
In file included from parser.y:6:
In file included from src/AST/StatementList.hpp:6:
In file included from src/AST/Statement.hpp:4:
src/AST/Value.hpp:4:10: fatal error: 'boost/variant.hpp' file not found
#include <boost/variant.hpp>
         ^
1 error generated.
make: *** [all] Error 1
FaZe-Machine:yoloswag420-master Hayzam$ sudo make
Password:
c++ -std=c++1y -g -I/usr/local/include -I./extlibs/StringUtils/include -Wno-deprecated-register src/AST/BinaryOperatorNode.cpp src/AST/CommandNode.cpp src/AST/IdentifierNode.cpp src/AST/Statement.cpp src/AST/UnaryOperatorNode.cpp src/AST/VariableDeclNode.cpp src/Interpreter.cpp src/lexer.cpp src/main.cpp src/parser.cpp -o ys420i
In file included from src/AST/BinaryOperatorNode.cpp:1:
In file included from src/AST/BinaryOperatorNode.hpp:4:
In file included from src/AST/Node.hpp:8:
src/AST/Value.hpp:4:10: fatal error: 'boost/variant.hpp' file not found
#include <boost/variant.hpp>
         ^
1 error generated.
In file included from src/AST/CommandNode.cpp:1:
In file included from src/AST/CommandNode.hpp:4:
In file included from src/AST/Node.hpp:8:
src/AST/Value.hpp:4:10: fatal error: 'boost/variant.hpp' file not found
#include <boost/variant.hpp>
         ^
1 error generated.
In file included from src/AST/IdentifierNode.cpp:1:
In file included from src/AST/IdentifierNode.hpp:6:
In file included from src/AST/Node.hpp:8:
src/AST/Value.hpp:4:10: fatal error: 'boost/variant.hpp' file not found
#include <boost/variant.hpp>
         ^
1 error generated.
In file included from src/AST/Statement.cpp:1:
In file included from src/AST/Statement.hpp:4:
src/AST/Value.hpp:4:10: fatal error: 'boost/variant.hpp' file not found
#include <boost/variant.hpp>
         ^
1 error generated.
In file included from src/AST/UnaryOperatorNode.cpp:1:
In file included from src/AST/UnaryOperatorNode.hpp:4:
In file included from src/AST/Node.hpp:8:
src/AST/Value.hpp:4:10: fatal error: 'boost/variant.hpp' file not found
#include <boost/variant.hpp>
         ^
1 error generated.
In file included from src/AST/VariableDeclNode.cpp:1:
In file included from src/AST/VariableDeclNode.hpp:4:
In file included from src/AST/Node.hpp:8:
src/AST/Value.hpp:4:10: fatal error: 'boost/variant.hpp' file not found
#include <boost/variant.hpp>
         ^
1 error generated.
In file included from src/Interpreter.cpp:1:
In file included from src/interpreter.hpp:9:
In file included from src/AST/AST.hpp:4:
src/AST/Value.hpp:4:10: fatal error: 'boost/variant.hpp' file not found
#include <boost/variant.hpp>
         ^
1 error generated.
lexer.l:4:10: fatal error: 'boost/lexical_cast/try_lexical_convert.hpp' file not found
#include <boost/lexical_cast/try_lexical_convert.hpp>
         ^
1 error generated.
In file included from src/main.cpp:5:
In file included from parser.y:26:
In file included from src/AST/AST.hpp:4:
src/AST/Value.hpp:4:10: fatal error: 'boost/variant.hpp' file not found
#include <boost/variant.hpp>
         ^
1 error generated.
In file included from parser.y:6:
In file included from src/AST/StatementList.hpp:6:
In file included from src/AST/Statement.hpp:4:
src/AST/Value.hpp:4:10: fatal error: 'boost/variant.hpp' file not found
#include <boost/variant.hpp>
         ^
1 error generated.
make: *** [all] Error 1

**Comment by miguelmartin75** [comment]
I should probably have made my makefile a bit nicer, but the flag `-I/usr/local/include` is essentially where my boost is installed (via homebrew), so you'd have to change it to wherever macports installed it. Seems that I forgot that I also use `boost.variant`. You also need a fairly recent version of boost (I think you need 1.56 or above) for `boost:: try_lexical_convert` or maybe that's just for the header `boost/lexical_cast/try_lexical_convert.hpp`, I'm not sure.

**Comment by Fazelesswhite** [comment]
Thanks buddy, I'll give a try now :)

**Comment by Fazelesswhite** [comment]
I used homebrew and tried to make it, it worked like a charm :D

**Comment by miguelmartin75** [comment]
No worries :)
